name: Feature 🚀
description: 새로운 기능을 빠르게 공유하세요.
title: "[feat]: "
labels: ["feature"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: textarea
    id: work-process
    attributes:
      label: 구현할 기능
      description: 어떤 기능을 구현할지 알려주세요.
      placeholder: 반복적인 명령어를 자동화하는 스크립트를 작성합니다.
    validations:
      required: true
  - type: textarea
    id: detail-work
    attributes:
      label: 상세작업내용
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: ⌛️ 예상소요시간
    validations:
      required: true
