name: quick-issue-template🚀
description: issue-template
title: '[feat] 소셜 로그인 개발'
labels: ['feat']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🤷 구현할 기능
        
        ex) 소셜 로그인 기능을 개발합니다.
  - type: markdown
    attributes:
      value: |
        ## 🔨 상세 작업 내용

  - type: checklist
    attributes:
      options:
        - 작업1
        - 작업2
        - 작업3

  - type: markdown
    attributes:
      value: |
        ## ⏰ 예상 소요 기간
        
        ex) 8시간
