name: quick-issue-template🚀
description: issue-template
title: '[feat] 소셜 로그인 개발'
labels: ['feat']
assignees: []

body:
  - type: textarea
    attributes:
      value: |
        🤷 구현할 기능
        
        ex) 소셜 로그인 기능을 개발합니다.
  - type: textarea
    attributes:
      value: |
       🔨 상세 작업 내용
  - type: checkboxes
    attributes:
      label: 작업 목록
      options:
        - label: 작업1
          required: false
        - label: 작업2
          required: false
        - label: 작업3
          required: false
  - type: textarea
    attributes:
      value: |
        ⏰ 예상 소요 기간
        
        ex) 8시간
